language: node_js
node_js:
  - 13.14.0
cache: npm

install:
  - npm ci
script:
  - npm test
  - npm run build
before_deploy:
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
